name: Orchestration Build and Test

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'module/**'
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  build-web:
    strategy:
      matrix:
        include:
          - name: web-pos

    uses: ./.github/workflows/node-build.yml
    with:
      name: ${{ matrix.name }}

 